bigpanther/shipanther

lib/bloc/auth/auth_bloc.dart
lib/bloc/auth/auth_state.dart
lib/bloc/tenant/tenant_bloc.dart
lib/bloc/tenant/tenant_event.dart
lib/bloc/tenant/tenant_state.dart
lib/data/tenant/remote_tenant_repository.dart
lib/data/tenant/tenant_repository.dart
lib/screens/home.dart
lib/screens/home_screen.dart
lib/screens/signin_or_register_page.dart
lib/widgets/extra_actions_button.dart
lib/widgets/filter_button.dart

When a superadmin logs in, they are redirected to Tenants screen for now. Implements #28

Add tenant screens 

---

lib/bloc/auth/auth_bloc.dart
lib/bloc/auth/auth_event.dart
lib/data/auth/firebase_auth_repository.dart
lib/main.dart
lib/screens/home.dart
lib/screens/signin_or_register_page.dart
lib/screens/tenant/detail.dart
lib/screens/tenant/list.dart

Update auth flow

---

lib/bloc/tenant/tenant_bloc.dart
lib/bloc/tenant/tenant_event.dart
lib/screens/home.dart
lib/screens/tenant/add_edit.dart
lib/screens/tenant/detail.dart
lib/screens/tenant/list.dart

Finish CRUD for tenants

---

android/app/build.gradle
android/app/src/main/AndroidManifest.xml
android/app/src/main/kotlin/ca/bigpanther/shipanther/Application.kt
lib/main.dart
lib/screens/detail_screen.dart
lib/screens/driver_home_page.dart
lib/screens/task_detail_test.dart
pubspec.lock
pubspec.yaml

Check if notification working or not from firestore.
-Go to grow/cloudMessaging.
- Tap on 'New Notification'
- Enter notification title and notification text.
-Click on next to go to Target section and choose your app.
- No changes in scheduling and conversion events.
- In additional option, provide key value pair as follow
- 'click_action': 'FLUTTER_NOTIFICATION_CLICK'
- 'id': '1'
- 'from':'A'
- 'to':'B'
- 'containerName':'ABC'
- 'pickupTime': '9AM'
- click on review and then publish
new notification should be generated

Notification test

---

ios/Podfile.lock
lib/bloc/customer/customer_bloc.dart
lib/bloc/customer/customer_event.dart
lib/bloc/customer/customer_state.dart
lib/data/customer/customer_repository.dart
lib/data/customer/remote_customer_repository.dart
lib/l10n/shipanther_localization.dart
lib/main.dart
lib/screens/customer/add_edit.dart
lib/screens/customer/home.dart
lib/screens/customer/list.dart
lib/screens/tenant/add_edit.dart
lib/screens/terminal/add_edit.dart
lib/widgets/shipanther_scaffold.dart

Add customer

---

lib/data/container/remote_container_repository.dart
lib/data/customer/remote_customer_repository.dart
lib/data/tenant/remote_tenant_repository.dart
lib/data/terminal/remote_terminal_repository.dart
lib/widgets/shipanther_scaffold.dart
pubspec.lock
pubspec.yaml

It is now possible to get user profile info on runtime

Update the sdk

---

lib/bloc/user/user_bloc.dart
lib/bloc/user/user_event.dart
lib/data/auth/auth_repository.dart
lib/data/auth/firebase_auth_repository.dart
lib/data/user/remote_user_repository.dart
lib/data/user/user_repository.dart
lib/main.dart
lib/screens/signin_or_register_page.dart

Register device token on registration

---

lib/bloc/auth/auth_bloc.dart
lib/bloc/auth/auth_event.dart
lib/data/auth/auth_repository.dart
lib/data/auth/firebase_auth_repository.dart
lib/l10n/shipanther_localization.dart
lib/screens/none_home.dart
lib/screens/signin_or_register_page.dart

Add preferred name

---

lib/bloc/user/user_bloc.dart
lib/bloc/user/user_event.dart
lib/bloc/user/user_state.dart
lib/data/user/remote_user_repository.dart
lib/data/user/user_repository.dart
lib/screens/carrier/add_edit.dart
lib/screens/carrier/home.dart
lib/screens/carrier/list.dart
lib/screens/container/home.dart
lib/screens/customer/add_edit.dart
lib/screens/customer/home.dart
lib/screens/order/add_edit.dart
lib/screens/order/home.dart
lib/screens/order/list.dart
lib/screens/tenant/list.dart
lib/screens/terminal/add_edit.dart
lib/screens/terminal/home.dart
lib/screens/terminal/list.dart
lib/screens/user/add_edit.dart
lib/screens/user/home.dart
lib/screens/user/list.dart
lib/widgets/shipanther_scaffold.dart
lib/widgets/tenant_selector.dart

Add user management

---

lib/widgets/shipanther_scaffold.dart

Order not needed for role none

---

lib/bloc/user/user_bloc.dart
lib/data/api/remote_api_repository.dart
lib/screens/carrier/add_edit.dart
lib/screens/container/add_edit.dart
lib/screens/customer/add_edit.dart
lib/screens/order/add_edit.dart
lib/screens/super_admin_home.dart
lib/screens/tenant/add_edit.dart
lib/screens/terminal/add_edit.dart
lib/screens/user/add_edit.dart

Fix user perms for superAdmin

---

.github/CODEOWNERS
.github/workflows/ci.yaml
lib/extensions/carrier_extension.dart
lib/extensions/tenant_extension.dart
lib/extensions/terminal_extension.dart
lib/extensions/user_extension.dart
lib/screens/api_login.dart
lib/screens/none_home.dart
lib/screens/signin_or_register_page.dart
lib/screens/verify_email.dart
lib/widgets/shipanther_scaffold.dart

Add Analyze ci

---

android/app/build.gradle
android/build.gradle
ios/Podfile.lock
ios/Runner.xcodeproj/project.pbxproj
lib/main_common.dart
pubspec.lock
pubspec.yaml

Add crashlytics

---

lib/screens/customer/add_edit.dart
lib/widgets/selectors.dart

Fix customer screen crash

---

lib/bloc/auth/auth_bloc.dart
lib/bloc/auth/auth_state.dart
lib/extensions/auth_type_selector_extension.dart
lib/extensions/carrier_extension.dart
lib/extensions/container_extension.dart
lib/extensions/order_extension.dart
lib/extensions/tenant_extension.dart
lib/extensions/terminal_extension.dart
lib/extensions/user_extension.dart
lib/screens/carrier/add_edit.dart
lib/screens/carrier/list.dart
lib/screens/container/add_edit.dart
lib/screens/customer/add_edit.dart
lib/screens/order/add_edit.dart
lib/screens/signin_or_register_form.dart
lib/screens/tenant/add_edit.dart
lib/screens/tenant/list.dart
lib/screens/terminal/add_edit.dart
lib/screens/terminal/list.dart
lib/screens/user/add_edit.dart
lib/screens/user/list.dart
lib/widgets/smart_select.dart

Lighten modal background

---

lib/widgets/smart_select.dart

Fix selector title

---

i18n/intl_messages_pa.arb

updated all EN strings into punjabi. Please review.

Update punjabi strings

---

lib/screens/carrier/add_edit.dart
lib/screens/container/add_edit.dart
lib/screens/container/list.dart
lib/screens/customer/add_edit.dart
lib/screens/order/add_edit.dart
lib/screens/terminal/add_edit.dart
lib/screens/user/add_edit.dart
lib/widgets/selectors.dart

typehead issue resolved

---

lib/screens/back_office_home.dart
lib/screens/carrier/home.dart
lib/screens/carrier/list.dart
lib/screens/customer/home.dart
lib/screens/customer/list.dart
lib/screens/driver_home.dart
lib/screens/order/add_edit.dart
lib/screens/order/home.dart
lib/screens/order/list.dart
lib/screens/super_admin_home.dart
lib/screens/terminal/home.dart
lib/screens/terminal/list.dart
lib/screens/user/home.dart
lib/screens/user/list.dart
pubspec.lock
pubspec.yaml

Fix orders details with customer value

---

lib/screens/container/add_edit.dart

Reservation time and lfd on edit screen

---

lib/widgets/shipanther_scaffold.dart
pubspec.lock
pubspec.yaml

Add icon for container

---

lib/screens/container/add_edit.dart
lib/screens/container/home.dart
lib/screens/container/list.dart
lib/screens/order/add_edit.dart
lib/screens/order/home.dart
lib/screens/order/list.dart
lib/screens/tenant/list.dart
lib/widgets/selectors.dart

Fix selected fields for typeahead

---

lib/extensions/container_extension.dart
lib/helper/text_widget.dart
lib/screens/back_office_home.dart
lib/screens/carrier/list.dart
lib/screens/container/add_edit.dart
lib/screens/container/driver_list.dart
lib/screens/container/home.dart
lib/screens/container/list.dart
lib/screens/customer/home.dart
lib/screens/customer/list.dart
lib/screens/customer_home.dart
lib/screens/driver_home.dart
lib/screens/none_home.dart
lib/screens/order/list.dart
lib/screens/profile.dart
lib/screens/super_admin_home.dart
lib/screens/tenant/list.dart
lib/screens/terminal/list.dart
lib/screens/user/list.dart
lib/widgets/shipanther_scaffold.dart

Driver screen

---

lib/screens/container/add_edit.dart

Add limit to serial number

---

lib/extensions/container_extension.dart
lib/screens/carrier/list.dart
lib/screens/container/add_edit.dart
lib/screens/container/list.dart
lib/screens/customer/list.dart
lib/screens/order/add_edit.dart
lib/screens/tenant/home.dart
lib/screens/tenant/list.dart
lib/screens/terminal/list.dart
lib/screens/user/list.dart
pubspec.yaml

Fixes order and container screen

---

lib/l10n/shipanther_localization.dart
lib/screens/container/driver_list.dart

add alert prompt

---

lib/widgets/filter_button.dart

Add ability to clear filters

---

.github/workflows/ci.yaml
ios/Podfile.lock
lib/screens/api_login.dart
lib/screens/carrier/home.dart
lib/screens/container/home.dart
lib/screens/customer/home.dart
lib/screens/customer_home.dart
lib/screens/driver_home.dart
lib/screens/order/home.dart
lib/screens/signin_or_register_page.dart
lib/screens/super_admin_home.dart
lib/screens/terminal/home.dart
lib/screens/user/home.dart
lib/widgets/theme.dart
pubspec.lock
pubspec.yaml

To run the webapp, flutter beta channel is required.
A new stable version of flutter would likely land in Q1 2021. In order to get the web to work, see https://flutter.dev/web
@anshul2401 You can also start using flutter beta channel.

Move to beta channel

---

ios/Podfile.lock
lib/main_common.dart
pubspec.lock
pubspec.yaml

Add google analytics

---

lib/l10n/shipanther_localization.dart
lib/widgets/filter_button.dart

It is not passed to the onselected callback

Fix clear option on filter

---

Makefile
android/app/build.gradle
android/build.gradle
android/gradle/wrapper/gradle-wrapper.properties

relates the issue described in https://github.com/flutter/flutter/issues/72592

Fix android build

---

ios/Runner.xcodeproj/project.pbxproj
lib/main_common.dart
lib/screens/carrier/add_edit.dart
lib/screens/customer/add_edit.dart
lib/screens/order/add_edit.dart
lib/screens/profile.dart
lib/screens/reset_password.dart
lib/screens/shipment/add_edit.dart
lib/screens/signin_or_register_form.dart
lib/screens/terminal/add_edit.dart
lib/screens/user/add_edit.dart
lib/screens/verify_email.dart

dquote> async on keypress caused falilure on ios with
dquote> [LayoutConstraints] Unable to simultaneously satisfy constraints.
Probably at least one of the constraints in the following list is one you don't want.
Try this:
(1) look at each constraint and try to figure out which you don't expect;
(2) find the code that added the unwanted constraint or constraints and fix it.
(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints)
(
"<NSAutoresizingMaskLayoutConstraint:0x283e06080 h=--& v=--& _UIButtonBarButton:0x11fc0c0b0.height == 0   (active)>",
"<NSLayoutConstraint:0x283e05900 V:|-(6)-[_UIUCBKBSelectionBackground:0x123b4c160]   (active, names: …

Fix ios crashes

---

lib/l10n/shipanther_localization.dart
lib/screens/carrier/add_edit.dart
lib/screens/carrier/list.dart
lib/screens/customer/add_edit.dart
lib/screens/customer/list.dart
lib/screens/order/add_edit.dart
lib/screens/order/list.dart
lib/screens/shipment/add_edit.dart
lib/screens/shipment/list.dart
lib/screens/tenant/add_edit.dart
lib/screens/tenant/list.dart
lib/screens/terminal/add_edit.dart
lib/screens/terminal/list.dart
lib/screens/user/add_edit.dart
lib/screens/user/list.dart
lib/widgets/selectors.dart

Add basic validators

---

lib/main_common.dart
lib/widgets/theme.dart
pubspec.lock
pubspec.yaml

Thanks to @rydmike for the awesome package.
Closes #136

Add both light and dark themes

---

i18n/intl_messages_pa.arb

Please review new updated punjabi strings @harsimranmaan

updated punjabi strings

---

lib/l10n/locales/messages_all.dart
lib/screens/api_login.dart
lib/screens/verify_email.dart

Center the error message text

---

ios/Runner/Info.plist

Fix ios orientation to portrait only

---

lib/screens/shipment/add_edit.dart

Fix shipment screen

---

lib/screens/carrier/add_edit.dart
lib/screens/customer/add_edit.dart
lib/screens/order/add_edit.dart
lib/screens/shipment/add_edit.dart
lib/screens/tenant/add_edit.dart
lib/screens/terminal/add_edit.dart
lib/screens/user/add_edit.dart

Fix add icon

---

ios/Podfile.lock
ios/Runner/Info.plist
lib/data/auth/remote_auth_repository.dart
lib/data/shipment/shipment_repository.dart
lib/extensions/shipment_extension.dart
lib/screens/none_home.dart
lib/screens/shipment/driver_list.dart
lib/screens/signin_or_register_form.dart
lib/widgets/shipanther_scaffold.dart
pubspec.lock
pubspec.yaml

Add ability to upload shipment receipts

---

.github/workflows/cla.yaml

Validates https://github.com/cla-assistant/github-action/issues/68

Update CLA action

---

Makefile
ios/Podfile.lock
lib/widgets/shipanther_scaffold.dart
pubspec.lock
pubspec.yaml

Update dependencies to null-safety

---

.github/workflows/ci.yaml
Makefile
android/app/build.gradle
android/build.gradle
ios/Podfile.lock
lib/extensions/shipment_extension.dart
lib/screens/carrier/add_edit.dart
lib/screens/carrier/list.dart
lib/screens/customer/add_edit.dart
lib/screens/customer/list.dart
lib/screens/order/add_edit.dart
lib/screens/order/list.dart
lib/screens/profile.dart
lib/screens/shipment/add_edit.dart
lib/screens/shipment/driver_list.dart
lib/screens/shipment/list.dart
lib/screens/signin_or_register_form.dart
lib/screens/tenant/add_edit.dart
lib/screens/tenant/list.dart
lib/screens/terminal/add_edit.dart
lib/screens/terminal/list.dart
lib/screens/user/add_edit.dart
pubspec.lock
pubspec.yaml
web/index.html

Closes #278
It is still not ready for sound null-safety as some packages haven't been migrated.

Add flutter 2.0 support

---

lib/widgets/selectors.dart
pubspec.lock
pubspec.yaml

Fix picker direction

---

lib/helper/colon.dart
lib/screens/carrier/add_edit.dart
lib/screens/shipment/add_edit.dart

Closes #203
The datetime is now translated back to user's timezone for display

fix timezone display issue

---

android/app/src/main/AndroidManifest.xml
ios/Podfile.lock

Fix issues with Android sdk 30+

---

ios/Podfile.lock
lib/bloc/shipment/shipment_bloc.dart
lib/bloc/shipment/shipment_state.dart
lib/extensions/shipment_extension.dart
lib/screens/shipment/add_edit.dart
lib/screens/shipment/home.dart
lib/screens/shipment/list.dart
pubspec.lock
pubspec.yaml

Rename Out Going to Outbound

---

.firebaserc
.gitignore
Makefile
firebase.json

Closes #291
CI changes would follow in a separate PR.

Deploy shipanther web app

---

lib/screens/carrier/add_edit.dart
lib/screens/order/add_edit.dart
lib/screens/shipment/add_edit.dart
lib/screens/shipment/driver_list.dart
lib/screens/tenant/add_edit.dart
lib/screens/terminal/add_edit.dart
lib/screens/user/add_edit.dart
lib/widgets/smart_select.dart

Fix modal color to match theme
